config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'ticket_viewer#index'
  post '/singleticket',  to: 'ticket_viewer#singleticket'
  get '/singleticket',  to: 'ticket_viewer#singleticket'
  
  get '/alltickets', to: 'ticket_viewer#alltickets'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ticket_viewer_controller.rb
require 'rubygems'
require 'json'
require 'net/http'
require 'httparty'
  


class TicketViewerController < ApplicationController
  include HTTParty
  def alltickets
    auth = {:username => "jeffphan8816@gmail.com", :password => "Aq123ew4rft6yh@@"}
    @tickets = []
    base_url = 'https://jeffphan8816.zendesk.com/api/v2/tickets'
    @response = HTTParty.get(base_url, :basic_auth => auth).parsed_response
    if !@response['error'].nil?
      puts @response['error']
      flash[:notice] = "#{@response['error']}"
    else
      if @response['tickets'].first.nil?
        flash[:notice] = "There is no ticket at the moment!"
      else
        loop do
          getallticket(@response)
          if !@response['next_page'].nil?
            @response = HTTParty.get(@response['next_page'], :basic_auth => auth).parsed_response
          else
            break
          end
        end
      end
    end
  end
  
  def singleticket
    base_url = 'https://jeffphan8816.zendesk.com/api/v2/tickets'
    ticketid = params.permit(:id)
    base_url = base_url + '/' + ticketid['id']
    auth = {:username => "jeffphan8816@gmail.com", :password => "Aq123ew4rft6yh@@"}
    @response = HTTParty.get(base_url, :basic_auth => auth).parsed_response
    if !@response['error'].nil?
      puts @response['error']
      flash[:notice] = "#{@response['error']}"
    else
      @ticket = @response['ticket']
      if !@ticket.nil?  
        render 'ticket_viewer/singleticket', :locals => {:ticket => @ticket}
      end
    end
  end
  
  def getallticket(response)
    if !response['tickets'].nil?
      @response['tickets'].each do |t|
        @tickets.append(t)
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_viewer_helper.rb
module TicketViewerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketviewer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <%= yield %>
  </body>
</html>

app/views/ticket_viewer/alltickets.erb
<h1>All tickets</h1>
<%= flash[:notice] %>
<% if !@tickets.nil? %>
  <% @tickets.each do |t| %>
    <p>Ticket: <%=t['id']%> | Subject: <%= t['subject'] %> | Opened by: <%=t['submitter_id']%> | On: <%=t['created_at']%></p> 
  <%end%>
<% end %>
<br>
<%= link_to 'Back to home page', root_path %>

app/views/ticket_viewer/error.html.erb
<p><%= @error %></p>

app/views/ticket_viewer/index.html.erb
<div class = "container">
  <h1>View single ticket</h1>
  <%= form_tag 'singleticket' do %>

  <h4>Id of ticket</h4>
  <div class="field form-control">
    <%= number_field_tag :id,nil, :required => true %>
  </div>
  
  <div class="actions">
    <%= submit_tag "View", class: "btn btn-primary"%>
  </div>
<% end %>
</div>



<%= link_to 'Click here to view all tickets', alltickets_path %>

app/views/ticket_viewer/singleticket.html.erb
<h1>Single Ticket</h1>
<%= flash[:notice] %>
<% if !@ticket.nil? %>
  <p>Ticket: <%= @ticket['id']%> | Subject: <%= @ticket['subject'] %> | Opened by: <%=@ticket['submitter_id']%> | On: <%=@ticket['created_at']%></p> 
<%end%>

<br>
<%= link_to 'Back to home page', root_path %>